# Generated By: Claude Code (Claude Opus 4.7 (1M context))

.PHONY: check help clean format install install-dev uninstall run build-image run-image push-image

PACKAGE_NAME ?= claude_quota_exporter
PROJECT_NAME ?= claude-quota-exporter
SRC_DIR ?= src/$(PACKAGE_NAME)
CONFIG_FILE ?= ./config.example.json
IMAGE_NAME ?= $(PROJECT_NAME)
IMAGE_TAG ?= $(shell sed -n 's/^version *= *"\(.*\)"/\1/p' pyproject.toml)
REGISTRY ?= ghcr.io/jewzaam

# Container builder: prefer docker, fall back to podman. Override with
# DOCKER=<path> when neither is on PATH.
DOCKER ?= $(shell command -v docker 2>/dev/null || command -v podman 2>/dev/null)

# Local container verification (run-image). Override per-environment.
HOST_PORT ?= 127.0.0.1:9180
CREDS_FILE ?= $(HOME)/.claude/.credentials.json
IMAGE_CONFIG_FILE ?= $(CURDIR)/config.local.json

ifeq ($(OS),Windows_NT)
    PY_SYS ?= py -3
    VENV_DIR ?= .venv
    PYTHON ?= $(VENV_DIR)/Scripts/python.exe
else
    PY_SYS ?= python3
    VENV_DIR ?= .venv
    PYTHON ?= $(VENV_DIR)/bin/python
endif

-include make/test.mk

$(info venv: $(VENV_DIR))

check: test-format test-lint test-typecheck test-unit test-coverage  ## Run full quality gate (default)

.DEFAULT_GOAL := check

help:  ## Show available targets
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-32s\033[0m %s\n", $$1, $$2}'

$(PYTHON):
	$(PY_SYS) -m venv $(VENV_DIR)

clean:  ## Remove build artifacts and caches
	rm -rf build/ dist/ *.egg-info
	find . -type d -name __pycache__ -exec rm -r {} + 2>/dev/null || true
	find . -type f -name "*.pyc" -delete 2>/dev/null || true

format: install-dev  ## Rewrite sources with black
	$(PYTHON) -m black $(SRC_DIR) tests

install: install-dev  ## Install the package (editable)
	$(PYTHON) -m pip install -e .

install-dev: $(PYTHON)  ## Editable install + dev extras
	$(PYTHON) -m pip install -e ".[dev]"

uninstall:  ## Remove the editable install from the venv
	$(PYTHON) -m pip uninstall -y $(PROJECT_NAME)

run: install-dev  ## Run the exporter against $(CONFIG_FILE)
	$(PYTHON) -m $(PACKAGE_NAME) --config $(CONFIG_FILE)

build-image:  ## Build the OCI container image (docker or podman)
	@if [ -z "$(DOCKER)" ]; then echo "build-image: no container builder on PATH (docker or podman). Set DOCKER=<path> to override." >&2; exit 1; fi
	"$(DOCKER)" build -t $(IMAGE_NAME):$(IMAGE_TAG) -f deploy/Dockerfile .

run-image:  ## Run the built container locally with creds + config mounted
	@if [ -z "$(DOCKER)" ]; then echo "run-image: no container runtime on PATH (docker or podman). Set DOCKER=<path> to override." >&2; exit 1; fi
	@if [ ! -f "$(IMAGE_CONFIG_FILE)" ]; then echo "run-image: $(IMAGE_CONFIG_FILE) not found. Copy config.example.json to config.local.json and edit (set host=0.0.0.0, credentials_path=/var/run/claude/credentials.json)." >&2; exit 1; fi
	@if [ ! -f "$(CREDS_FILE)" ]; then echo "run-image: $(CREDS_FILE) not found. Override with CREDS_FILE=<path>." >&2; exit 1; fi
	"$(DOCKER)" run --rm --name $(PROJECT_NAME) \
	    -p $(HOST_PORT):9180 \
	    -v "$(abspath $(CREDS_FILE))":/var/run/claude/credentials.json:ro \
	    -v "$(abspath $(IMAGE_CONFIG_FILE))":/etc/claude-quota-exporter/config.json:ro \
	    $(IMAGE_NAME):$(IMAGE_TAG)

push-image: build-image  ## Tag + push the OCI image to $(REGISTRY)
	@if [ -z "$(DOCKER)" ]; then echo "push-image: no container runtime on PATH (docker or podman). Set DOCKER=<path> to override." >&2; exit 1; fi
	"$(DOCKER)" tag $(IMAGE_NAME):$(IMAGE_TAG) $(REGISTRY)/$(IMAGE_NAME):$(IMAGE_TAG)
	"$(DOCKER)" tag $(IMAGE_NAME):$(IMAGE_TAG) $(REGISTRY)/$(IMAGE_NAME):latest
	"$(DOCKER)" push $(REGISTRY)/$(IMAGE_NAME):$(IMAGE_TAG)
	"$(DOCKER)" push $(REGISTRY)/$(IMAGE_NAME):latest

