# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Shared fixtures and safety guards for all tests.

Autouse guards block real subprocess, network, and out-of-tmp filesystem
writes. Mirrors the agentpulse pattern.
"""

import subprocess
import urllib.request
from pathlib import Path
from unittest.mock import patch

import pytest

_PROJECT_ROOT = Path(__file__).resolve().parent.parent


@pytest.fixture(autouse=True)
def _block_subprocess():  # type: ignore[no-untyped-def]
    """Block subprocess globally — no real commands in tests."""

    def _blocked(*args, **kwargs):  # type: ignore[no-untyped-def]
        cmd = args[0] if args else kwargs.get("args", "?")
        raise RuntimeError(f"subprocess blocked by conftest: {cmd!r}. Mock it instead.")

    with (
        patch.object(subprocess, "run", side_effect=_blocked),
        patch.object(subprocess, "Popen", side_effect=_blocked),
        patch.object(subprocess, "call", side_effect=_blocked),
        patch.object(subprocess, "check_call", side_effect=_blocked),
        patch.object(subprocess, "check_output", side_effect=_blocked),
    ):
        yield


@pytest.fixture(autouse=True)
def _block_real_http(monkeypatch: pytest.MonkeyPatch) -> None:
    """Block real HTTP requests via urllib. Tests must patch explicitly."""

    def _blocked(*args, **kwargs):  # type: ignore[no-untyped-def]
        raise RuntimeError(
            "HTTP blocked by conftest. Patch urllib.request.urlopen instead."
        )

    monkeypatch.setattr(urllib.request, "urlopen", _blocked)


@pytest.fixture(autouse=True)
def _block_real_filesystem(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Prevent tests from writing outside tmp_path."""

    def _is_allowed(path: Path) -> bool:
        resolved = path.resolve()
        return str(resolved).startswith(str(tmp_path)) or str(resolved).startswith(
            str(_PROJECT_ROOT / ".venv")
        )

    def _guard(original):  # type: ignore[no-untyped-def]
        def guarded(self, *args, **kwargs):  # type: ignore[no-untyped-def]
            if not _is_allowed(self):
                raise PermissionError(f"Test tried to write outside tmp_path: {self}")
            return original(self, *args, **kwargs)

        return guarded

    for method in (
        "write_text",
        "write_bytes",
        "rename",
        "unlink",
        "rmdir",
        "mkdir",
    ):
        monkeypatch.setattr(Path, method, _guard(getattr(Path, method)))
