# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Tests for fetcher: throttling, backoff, extraction."""

import json
import urllib.error
from pathlib import Path
from unittest.mock import patch

import pytest

from claude_quota_exporter.fetcher import (
    Fetcher,
    _iso_to_epoch_seconds,
    extract_buckets,
    fetch_from_api,
)

SAMPLE_RAW = {
    "five_hour": {
        "utilization": 11.0,
        "resets_at": "2026-04-13T07:00:00+00:00",
    },
    "seven_day": {
        "utilization": 8.0,
        "resets_at": "2026-04-19T13:00:00+00:00",
    },
    "seven_day_opus": {
        "utilization": 4.0,
        "resets_at": "2026-04-19T13:00:00+00:00",
    },
}


class TestIsoToEpoch:
    def test_valid_iso(self) -> None:
        v = _iso_to_epoch_seconds("2026-04-13T07:00:00+00:00")
        assert isinstance(v, float)
        assert v > 0

    @pytest.mark.parametrize("bad", [None, "", "not a date", 123])
    def test_invalid(self, bad: object) -> None:
        assert _iso_to_epoch_seconds(bad) is None


class TestExtractBuckets:
    def test_normalizes_utilization_to_ratio(self) -> None:
        out = extract_buckets(SAMPLE_RAW)
        assert out["five_hour"]["utilization"] == pytest.approx(0.11)
        assert out["seven_day"]["utilization"] == pytest.approx(0.08)
        assert out["seven_day_opus"]["utilization"] == pytest.approx(0.04)

    def test_dynamic_bucket_picked_up(self) -> None:
        raw = {
            "novel_bucket": {
                "utilization": 50.0,
                "resets_at": "2026-04-19T13:00:00+00:00",
            }
        }
        out = extract_buckets(raw)
        assert "novel_bucket" in out
        assert out["novel_bucket"]["utilization"] == pytest.approx(0.5)

    def test_non_dict_top_level_skipped(self) -> None:
        raw = {"meta": "ignore me", "five_hour": SAMPLE_RAW["five_hour"]}
        out = extract_buckets(raw)
        assert "meta" not in out
        assert "five_hour" in out

    def test_null_resets_at(self) -> None:
        raw = {"five_hour": {"utilization": 0.0, "resets_at": None}}
        out = extract_buckets(raw)
        assert out["five_hour"]["utilization"] == 0.0
        assert out["five_hour"]["resets_at"] is None

    def test_missing_utilization_yields_none(self) -> None:
        raw = {"x": {"resets_at": "2026-04-19T13:00:00+00:00"}}
        out = extract_buckets(raw)
        assert out["x"]["utilization"] is None
        assert isinstance(out["x"]["resets_at"], float)


def _make_fetcher(tmp_path: Path, ttl: int = 120) -> Fetcher:
    creds_path = tmp_path / "creds.json"
    creds_path.write_text(
        json.dumps({"claudeAiOauth": {"accessToken": "sk-ant-oat01-AAA"}}),
        encoding="utf-8",
    )
    return Fetcher(
        credentials_path=creds_path,
        ttl_seconds=ttl,
        timeout_seconds=5,
        max_backoff_seconds=3600,
    )


class TestFetcherRefresh:
    def test_first_refresh_populates_cache(self, tmp_path: Path) -> None:
        f = _make_fetcher(tmp_path)
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=SAMPLE_RAW,
        ):
            assert f.refresh_if_due() is True
        assert f.cached_raw == SAMPLE_RAW
        assert f.success_count == 1
        assert f.failure_count == 0
        assert f.last_success_at > 0.0

    def test_ttl_blocks_second_refresh(self, tmp_path: Path) -> None:
        f = _make_fetcher(tmp_path, ttl=120)
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=SAMPLE_RAW,
        ) as mock:
            assert f.refresh_if_due() is True
            assert f.refresh_if_due() is False
        assert mock.call_count == 1

    def test_failure_increments_failure_counter(self, tmp_path: Path) -> None:
        f = _make_fetcher(tmp_path)
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=None,
        ):
            assert f.refresh_if_due() is False
        assert f.failure_count == 1
        assert f.success_count == 0
        assert f.cached_raw is None

    def test_backoff_blocks_immediate_retry(self, tmp_path: Path) -> None:
        f = _make_fetcher(tmp_path)
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=None,
        ) as mock:
            assert f.refresh_if_due() is False
            assert f.refresh_if_due() is False
        assert mock.call_count == 1

    def test_missing_creds_at_startup_skips_fetch(self, tmp_path: Path) -> None:
        f = Fetcher(
            credentials_path=tmp_path / "missing.json",
            ttl_seconds=120,
            timeout_seconds=5,
            max_backoff_seconds=3600,
        )
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=SAMPLE_RAW,
        ) as mock:
            assert f.refresh_if_due() is False
        mock.assert_not_called()
        assert f.has_credentials() is False
        assert f.success_count == 0

    def test_success_after_failure_resets_backoff(self, tmp_path: Path) -> None:
        f = _make_fetcher(tmp_path)
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=None,
        ):
            f.refresh_if_due()
        assert f._consecutive_failures == 1
        f._last_attempt_at = 0.0
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=SAMPLE_RAW,
        ):
            assert f.refresh_if_due() is True
        assert f._consecutive_failures == 0
        assert f.success_count == 1

    def test_creds_appear_mid_flight(self, tmp_path: Path) -> None:
        # Start with no creds file. First refresh skips. Then drop the
        # file in place; next refresh picks it up with no restart.
        creds_path = tmp_path / "creds.json"
        f = Fetcher(
            credentials_path=creds_path,
            ttl_seconds=120,
            timeout_seconds=5,
            max_backoff_seconds=3600,
        )
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=SAMPLE_RAW,
        ) as mock:
            assert f.refresh_if_due() is False
            mock.assert_not_called()
            assert f.has_credentials() is False
            creds_path.write_text(
                json.dumps({"claudeAiOauth": {"accessToken": "sk-ant-oat01-AAA"}}),
                encoding="utf-8",
            )
            assert f.has_credentials() is True
            assert f.refresh_if_due() is True
        assert f.cached_raw == SAMPLE_RAW
        assert f.success_count == 1

    def test_creds_disappear_mid_flight_retains_cache(self, tmp_path: Path) -> None:
        # Successful fetch populates cache. Remove the creds file; the
        # next attempt skips without clearing the cache. Operators keep
        # serving last-known-good values via /metrics.
        f = _make_fetcher(tmp_path, ttl=0)
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=SAMPLE_RAW,
        ) as mock:
            assert f.refresh_if_due() is True
        assert f.cached_raw == SAMPLE_RAW

        f._credentials_path.unlink()
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=SAMPLE_RAW,
        ) as mock:
            assert f.refresh_if_due() is False
            mock.assert_not_called()
        assert f.cached_raw == SAMPLE_RAW
        assert f.has_credentials() is False

    def test_has_credentials_reflects_live_state(self, tmp_path: Path) -> None:
        f = _make_fetcher(tmp_path)
        assert f.has_credentials() is True
        f._credentials_path.unlink()
        assert f.has_credentials() is False
        f._credentials_path.write_text(
            json.dumps({"claudeAiOauth": {"accessToken": "sk-ant-oat01-BBB"}}),
            encoding="utf-8",
        )
        assert f.has_credentials() is True

    def test_rotated_token_used_on_next_fetch(self, tmp_path: Path) -> None:
        # Token swapped on disk between fetches. Second fetch uses the
        # new value, proving no in-memory bearer cache survives across
        # calls.
        f = _make_fetcher(tmp_path, ttl=0)
        seen: list[str] = []

        def _capture(*, token: str, timeout_seconds: int) -> dict:
            seen.append(token)
            return SAMPLE_RAW

        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            side_effect=_capture,
        ):
            assert f.refresh_if_due() is True
            f._credentials_path.write_text(
                json.dumps({"claudeAiOauth": {"accessToken": "sk-ant-oat01-ROTATED"}}),
                encoding="utf-8",
            )
            assert f.refresh_if_due() is True
        assert seen == ["sk-ant-oat01-AAA", "sk-ant-oat01-ROTATED"]


class TestFetchFromApi:
    def test_success_returns_dict(self) -> None:
        class _R:
            def read(self):
                return b'{"five_hour": {"utilization": 1.0}}'

            def __enter__(self):
                return self

            def __exit__(self, *a):
                return False

        with patch(
            "claude_quota_exporter.fetcher.urllib.request.urlopen",
            return_value=_R(),
        ):
            result = fetch_from_api(token="tk", timeout_seconds=5)
        assert result == {"five_hour": {"utilization": 1.0}}

    def test_http_error_returns_none(self) -> None:
        import io

        def _raise(req, timeout=None):
            raise urllib.error.HTTPError(
                getattr(req, "full_url", "u"),
                401,
                "Unauthorized",
                {},
                io.BytesIO(b""),
            )

        with patch(
            "claude_quota_exporter.fetcher.urllib.request.urlopen",
            side_effect=_raise,
        ):
            result = fetch_from_api(token="tk", timeout_seconds=5)
        assert result is None

    def test_network_error_returns_none(self) -> None:
        with patch(
            "claude_quota_exporter.fetcher.urllib.request.urlopen",
            side_effect=urllib.error.URLError("down"),
        ):
            result = fetch_from_api(token="tk", timeout_seconds=5)
        assert result is None
