# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Tests for auth.py — Credentials and read_credentials."""

import json
from pathlib import Path

from claude_quota_exporter.auth import Credentials, read_credentials


def _full_creds_blob(
    access: str = "sk-ant-oat01-AAA",
    extras: dict | None = None,
) -> dict:
    payload: dict = {
        "claudeAiOauth": {
            "accessToken": access,
        }
    }
    if extras:
        payload["claudeAiOauth"].update(extras)
    return payload


class TestReadCredentials:
    def test_happy_path(self, tmp_path: Path) -> None:
        p = tmp_path / "creds.json"
        p.write_text(json.dumps(_full_creds_blob()), encoding="utf-8")
        creds = read_credentials(p)
        assert creds is not None
        assert isinstance(creds, Credentials)
        assert creds.access_token == "sk-ant-oat01-AAA"

    def test_unknown_sibling_fields_are_ignored(self, tmp_path: Path) -> None:
        # expiresAt, refreshToken, scopes etc. are tolerated but
        # silently dropped — the exporter consumes only accessToken.
        p = tmp_path / "creds.json"
        blob = _full_creds_blob(
            extras={
                "refreshToken": "sk-ant-ort01-IGNORED",
                "expiresAt": 1779580800694,
                "scopes": ["user:profile"],
                "subscriptionType": "max",
            }
        )
        p.write_text(json.dumps(blob), encoding="utf-8")
        creds = read_credentials(p)
        assert creds is not None
        assert creds.access_token == "sk-ant-oat01-AAA"

    def test_missing_file_returns_none(self, tmp_path: Path) -> None:
        assert read_credentials(tmp_path / "nope.json") is None

    def test_malformed_json_returns_none(self, tmp_path: Path) -> None:
        p = tmp_path / "creds.json"
        p.write_text("not json", encoding="utf-8")
        assert read_credentials(p) is None

    def test_missing_claudeAiOauth_block_returns_none(self, tmp_path: Path) -> None:
        p = tmp_path / "creds.json"
        p.write_text(json.dumps({"other": {}}), encoding="utf-8")
        assert read_credentials(p) is None

    def test_missing_access_token_returns_none(self, tmp_path: Path) -> None:
        p = tmp_path / "creds.json"
        p.write_text(
            json.dumps({"claudeAiOauth": {}}),
            encoding="utf-8",
        )
        assert read_credentials(p) is None

    def test_empty_access_token_returns_none(self, tmp_path: Path) -> None:
        p = tmp_path / "creds.json"
        p.write_text(
            json.dumps({"claudeAiOauth": {"accessToken": ""}}),
            encoding="utf-8",
        )
        assert read_credentials(p) is None

    def test_directory_path_returns_none(self, tmp_path: Path) -> None:
        # IsADirectoryError is an OSError subclass; must be swallowed.
        assert read_credentials(tmp_path) is None
