# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Tests for fetcher: throttling, backoff, extraction."""

import io
import json
import time
import urllib.error
from pathlib import Path
from unittest.mock import patch

import pytest

from claude_quota_exporter.fetcher import (
    FetchResult,
    Fetcher,
    _iso_to_epoch_seconds,
    extract_buckets,
    fetch_from_api,
)

SAMPLE_RAW = {
    "five_hour": {
        "utilization": 11.0,
        "resets_at": "2026-04-13T07:00:00+00:00",
    },
    "seven_day": {
        "utilization": 8.0,
        "resets_at": "2026-04-19T13:00:00+00:00",
    },
    "seven_day_opus": {
        "utilization": 4.0,
        "resets_at": "2026-04-19T13:00:00+00:00",
    },
}


def _ok(payload: dict | None = None) -> FetchResult:
    return FetchResult(status=200, payload=payload or SAMPLE_RAW)


def _fail(status: int = 0) -> FetchResult:
    return FetchResult(status=status, payload=None)


class TestIsoToEpoch:
    def test_valid_iso(self) -> None:
        v = _iso_to_epoch_seconds("2026-04-13T07:00:00+00:00")
        assert isinstance(v, float)
        assert v > 0

    @pytest.mark.parametrize("bad", [None, "", "not a date", 123])
    def test_invalid(self, bad: object) -> None:
        assert _iso_to_epoch_seconds(bad) is None


class TestExtractBuckets:
    def test_normalizes_utilization_to_ratio(self) -> None:
        out = extract_buckets(SAMPLE_RAW)
        assert out["five_hour"]["utilization"] == pytest.approx(0.11)
        assert out["seven_day"]["utilization"] == pytest.approx(0.08)
        assert out["seven_day_opus"]["utilization"] == pytest.approx(0.04)

    def test_dynamic_bucket_picked_up(self) -> None:
        raw = {
            "novel_bucket": {
                "utilization": 50.0,
                "resets_at": "2026-04-19T13:00:00+00:00",
            }
        }
        out = extract_buckets(raw)
        assert "novel_bucket" in out
        assert out["novel_bucket"]["utilization"] == pytest.approx(0.5)

    def test_non_dict_top_level_skipped(self) -> None:
        raw = {"meta": "ignore me", "five_hour": SAMPLE_RAW["five_hour"]}
        out = extract_buckets(raw)
        assert "meta" not in out
        assert "five_hour" in out

    def test_null_resets_at(self) -> None:
        raw = {"five_hour": {"utilization": 0.0, "resets_at": None}}
        out = extract_buckets(raw)
        assert out["five_hour"]["utilization"] == 0.0
        assert out["five_hour"]["resets_at"] is None

    def test_missing_utilization_yields_none(self) -> None:
        raw = {"x": {"resets_at": "2026-04-19T13:00:00+00:00"}}
        out = extract_buckets(raw)
        assert out["x"]["utilization"] is None
        assert isinstance(out["x"]["resets_at"], float)


def _make_fetcher(
    tmp_path: Path,
    ttl: int = 120,
    expires_at: float | None = None,
) -> Fetcher:
    creds_path = tmp_path / "creds.json"
    blob: dict = {"claudeAiOauth": {"accessToken": "sk-ant-oat01-AAA"}}
    if expires_at is not None:
        blob["claudeAiOauth"]["expiresAt"] = int(expires_at * 1000)
    creds_path.write_text(json.dumps(blob), encoding="utf-8")
    return Fetcher(
        credentials_path=creds_path,
        ttl_seconds=ttl,
        timeout_seconds=5,
        max_backoff_seconds=3600,
    )


class TestFetcherRefresh:
    def test_first_refresh_populates_cache(self, tmp_path: Path) -> None:
        f = _make_fetcher(tmp_path)
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=_ok(),
        ):
            assert f.refresh_if_due() is True
        assert f.cached_raw == SAMPLE_RAW
        assert f.success_count == 1
        assert f.failure_count == 0
        assert f.last_success_at > 0.0

    def test_ttl_blocks_second_refresh(self, tmp_path: Path) -> None:
        f = _make_fetcher(tmp_path, ttl=120)
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=_ok(),
        ) as mock:
            assert f.refresh_if_due() is True
            assert f.refresh_if_due() is False
        assert mock.call_count == 1

    def test_failure_increments_failure_counter(self, tmp_path: Path) -> None:
        f = _make_fetcher(tmp_path)
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=_fail(),
        ):
            assert f.refresh_if_due() is False
        assert f.failure_count == 1
        assert f.success_count == 0
        assert f.cached_raw is None

    def test_backoff_blocks_immediate_retry(self, tmp_path: Path) -> None:
        f = _make_fetcher(tmp_path)
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=_fail(),
        ) as mock:
            assert f.refresh_if_due() is False
            assert f.refresh_if_due() is False
        assert mock.call_count == 1

    def test_missing_creds_at_startup_skips_fetch(self, tmp_path: Path) -> None:
        f = Fetcher(
            credentials_path=tmp_path / "missing.json",
            ttl_seconds=120,
            timeout_seconds=5,
            max_backoff_seconds=3600,
        )
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=_ok(),
        ) as mock:
            assert f.refresh_if_due() is False
        mock.assert_not_called()
        assert f.has_credentials() is False
        assert f.success_count == 0

    def test_401_counts_as_failure_no_special_handling(self, tmp_path: Path) -> None:
        # No refresh logic; 401 is just another failure.
        f = _make_fetcher(tmp_path)
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=_fail(status=401),
        ):
            assert f.refresh_if_due() is False
        assert f.failure_count == 1

    def test_success_after_failure_resets_backoff(self, tmp_path: Path) -> None:
        f = _make_fetcher(tmp_path)
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=_fail(),
        ):
            f.refresh_if_due()
        assert f._consecutive_failures == 1
        f._last_attempt_at = 0.0
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=_ok(),
        ):
            assert f.refresh_if_due() is True
        assert f._consecutive_failures == 0
        assert f.success_count == 1


class TestFetchFromApiResult:
    def test_success_returns_dict_with_status_200(self) -> None:
        class _R:
            def read(self):
                return b'{"five_hour": {"utilization": 1.0}}'

            def __enter__(self):
                return self

            def __exit__(self, *a):
                return False

        with patch(
            "claude_quota_exporter.fetcher.urllib.request.urlopen",
            return_value=_R(),
        ):
            result = fetch_from_api(token="tk", timeout_seconds=5)
        assert isinstance(result, FetchResult)
        assert result.status == 200
        assert result.payload == {"five_hour": {"utilization": 1.0}}

    def test_401_returns_status_401_none_payload(self) -> None:
        def _raise(req, timeout=None):
            raise urllib.error.HTTPError(
                getattr(req, "full_url", "u"),
                401,
                "Unauthorized",
                {},
                io.BytesIO(b""),
            )

        with patch(
            "claude_quota_exporter.fetcher.urllib.request.urlopen",
            side_effect=_raise,
        ):
            result = fetch_from_api(token="tk", timeout_seconds=5)
        assert result.status == 401
        assert result.payload is None

    def test_network_error_returns_status_zero(self) -> None:
        with patch(
            "claude_quota_exporter.fetcher.urllib.request.urlopen",
            side_effect=urllib.error.URLError("down"),
        ):
            result = fetch_from_api(token="tk", timeout_seconds=5)
        assert result.status == 0
        assert result.payload is None


class TestAccessTokenExpiresAtAccessor:
    def test_zero_expires_at_returns_none(self, tmp_path: Path) -> None:
        # Minimum-viable creds (no expiresAt) → no expiry tracked.
        f = _make_fetcher(tmp_path)
        assert f.access_token_expires_at is None

    def test_nonzero_expires_at_returned_as_epoch_seconds(self, tmp_path: Path) -> None:
        target = time.time() + 7200
        f = _make_fetcher(tmp_path, expires_at=target)
        assert f.access_token_expires_at == pytest.approx(target)

    def test_no_creds_returns_none(self, tmp_path: Path) -> None:
        f = Fetcher(
            credentials_path=tmp_path / "missing.json",
            ttl_seconds=120,
            timeout_seconds=5,
            max_backoff_seconds=3600,
        )
        assert f.access_token_expires_at is None
