# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Tests for the Prometheus collector."""

import json
from pathlib import Path
from unittest.mock import patch

from prometheus_client import CollectorRegistry, generate_latest

from claude_quota_exporter.fetcher import Fetcher
from claude_quota_exporter.metrics import QuotaCollector

SAMPLE_RAW = {
    "five_hour": {
        "utilization": 11.0,
        "resets_at": "2026-04-13T07:00:00+00:00",
    },
    "seven_day": {
        "utilization": 8.0,
        "resets_at": "2026-04-19T13:00:00+00:00",
    },
    "seven_day_opus": {
        "utilization": 4.0,
        "resets_at": "2026-04-19T13:00:00+00:00",
    },
}


def _make_fetcher(tmp_path: Path) -> Fetcher:
    creds = tmp_path / "creds.json"
    creds.write_text(
        json.dumps({"claudeAiOauth": {"accessToken": "tk"}}),
        encoding="utf-8",
    )
    return Fetcher(
        credentials_path=creds,
        ttl_seconds=120,
        timeout_seconds=5,
        max_backoff_seconds=3600,
    )


def _render(fetcher: Fetcher) -> str:
    reg = CollectorRegistry()
    reg.register(QuotaCollector(fetcher=fetcher))
    return generate_latest(reg).decode("utf-8")


class TestQuotaCollector:
    def test_empty_cache_emits_definitions_only(self, tmp_path: Path) -> None:
        # Block the in-collector refresh attempt.
        f = _make_fetcher(tmp_path)
        with patch("claude_quota_exporter.fetcher.fetch_from_api", return_value=None):
            out = _render(f)
        assert "claude_quota_utilization" in out
        assert "claude_quota_resets_at_seconds" in out
        assert "claude_quota_fetch_failure_total 1.0" in out

    def test_populated_cache_emits_labeled_gauges(self, tmp_path: Path) -> None:
        f = _make_fetcher(tmp_path)
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=SAMPLE_RAW,
        ):
            out = _render(f)
        assert 'claude_quota_utilization{bucket="five_hour"} 0.11' in out
        assert 'claude_quota_utilization{bucket="seven_day"} 0.08' in out
        assert 'claude_quota_utilization{bucket="seven_day_opus"} 0.04' in out
        assert 'claude_quota_resets_at_seconds{bucket="five_hour"}' in out
        assert "claude_quota_fetch_success_total 1.0" in out
        assert "claude_quota_last_fetch_timestamp_seconds" in out

    def test_dynamic_bucket_surfaces(self, tmp_path: Path) -> None:
        f = _make_fetcher(tmp_path)
        novel = {
            "novel_bucket": {
                "utilization": 50.0,
                "resets_at": "2026-04-19T13:00:00+00:00",
            }
        }
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=novel,
        ):
            out = _render(f)
        assert 'claude_quota_utilization{bucket="novel_bucket"} 0.5' in out
