# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Tests for the config loader."""

import json
from pathlib import Path

import pytest

from claude_quota_exporter.config import (
    DEFAULT_CREDENTIALS_PATH,
    DEFAULT_FETCH_TTL_SECONDS,
    DEFAULT_HOST,
    DEFAULT_PORT,
    Settings,
)


def _write_cfg(path: Path, data: dict) -> Path:
    path.write_text(json.dumps(data), encoding="utf-8")
    return path


class TestSettingsFromConfig:
    def test_missing_file_raises(self, tmp_path: Path) -> None:
        with pytest.raises(FileNotFoundError):
            Settings.from_config(config_path=tmp_path / "nope.json")

    def test_empty_object_uses_defaults(self, tmp_path: Path) -> None:
        cfg = _write_cfg(tmp_path / "c.json", {})
        s = Settings.from_config(config_path=cfg)
        assert s.host == DEFAULT_HOST
        assert s.port == DEFAULT_PORT
        assert s.credentials_path == DEFAULT_CREDENTIALS_PATH
        assert s.fetch_ttl_seconds == DEFAULT_FETCH_TTL_SECONDS

    def test_overrides_applied(self, tmp_path: Path) -> None:
        cfg = _write_cfg(
            tmp_path / "c.json",
            {
                "host": "127.0.0.1",
                "port": 1234,
                "credentials_path": str(tmp_path / "creds.json"),
                "fetch_ttl_seconds": 30,
                "fetch_timeout_seconds": 5,
                "max_backoff_seconds": 600,
                "log_level": "debug",
            },
        )
        s = Settings.from_config(config_path=cfg)
        assert s.host == "127.0.0.1"
        assert s.port == 1234
        assert s.credentials_path == tmp_path / "creds.json"
        assert s.fetch_ttl_seconds == 30
        assert s.fetch_timeout_seconds == 5
        assert s.max_backoff_seconds == 600
        assert s.log_level == "DEBUG"

    def test_malformed_json_falls_back_to_defaults(self, tmp_path: Path) -> None:
        cfg = tmp_path / "c.json"
        cfg.write_text("not json", encoding="utf-8")
        s = Settings.from_config(config_path=cfg)
        assert s.port == DEFAULT_PORT
