# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Tests for the HTTP server routes via real socket binding on localhost."""

import json
import threading
from pathlib import Path
from unittest.mock import patch

import pytest
from prometheus_client import CollectorRegistry

from claude_quota_exporter.fetcher import Fetcher
from claude_quota_exporter.metrics import QuotaCollector
from claude_quota_exporter.server import build_server

SAMPLE_RAW = {
    "five_hour": {
        "utilization": 11.0,
        "resets_at": "2026-04-13T07:00:00+00:00",
    }
}


@pytest.fixture
def server_ctx(tmp_path: Path):
    creds = tmp_path / "creds.json"
    creds.write_text(
        json.dumps({"claudeAiOauth": {"accessToken": "tk"}}),
        encoding="utf-8",
    )
    fetcher = Fetcher(
        credentials_path=creds,
        ttl_seconds=120,
        timeout_seconds=5,
        max_backoff_seconds=3600,
    )
    registry = CollectorRegistry()
    registry.register(QuotaCollector(fetcher=fetcher))

    server = build_server(
        host="127.0.0.1",
        port=0,
        registry=registry,
        fetcher=fetcher,
    )
    port = server.server_address[1]
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        yield fetcher, port
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=2)


def _get(port: int, path: str) -> tuple[int, str]:
    # Bypass the conftest urllib block by going through the raw socket. The
    # conftest only patches urllib.request.urlopen used by the fetcher.
    import socket

    sock = socket.create_connection(("127.0.0.1", port), timeout=2)
    try:
        sock.sendall(f"GET {path} HTTP/1.0\r\nHost: 127.0.0.1\r\n\r\n".encode())
        chunks: list[bytes] = []
        while True:
            data = sock.recv(4096)
            if not data:
                break
            chunks.append(data)
    finally:
        sock.close()
    payload = b"".join(chunks).decode("utf-8", errors="replace")
    head, _, body = payload.partition("\r\n\r\n")
    status_line = head.split("\r\n", 1)[0]
    status = int(status_line.split(" ", 2)[1])
    return status, body


class TestRoutes:
    def test_healthz_always_ok(self, server_ctx) -> None:
        _, port = server_ctx
        status, body = _get(port, "/healthz")
        assert status == 200
        assert "ok" in body

    def test_readyz_503_before_first_fetch(self, server_ctx) -> None:
        fetcher, port = server_ctx
        with patch("claude_quota_exporter.fetcher.fetch_from_api", return_value=None):
            status, _ = _get(port, "/readyz")
        # No successful fetch has occurred.
        assert fetcher.last_success_at == 0.0
        assert status == 503

    def test_readyz_200_after_first_fetch(self, server_ctx) -> None:
        fetcher, port = server_ctx
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=SAMPLE_RAW,
        ):
            # /metrics scrape triggers the fetch.
            _get(port, "/metrics")
        assert fetcher.last_success_at > 0.0
        status, _ = _get(port, "/readyz")
        assert status == 200

    def test_metrics_endpoint_exposes_gauges(self, server_ctx) -> None:
        _, port = server_ctx
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=SAMPLE_RAW,
        ):
            status, body = _get(port, "/metrics")
        assert status == 200
        assert 'claude_quota_utilization{bucket="five_hour"} 0.11' in body

    def test_unknown_path_404(self, server_ctx) -> None:
        _, port = server_ctx
        status, _ = _get(port, "/whatever")
        assert status == 404
