# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Tests for the CLI entry point."""

import json
import logging
import sys
from pathlib import Path
from unittest.mock import patch

import pytest

from claude_quota_exporter.__main__ import (
    EXIT_ERROR,
    EXIT_SUCCESS,
    _configure_logging,
    _parse_args,
    _resolve_log_level,
    main,
)


def _write_cfg(tmp_path: Path, host: str = "127.0.0.1") -> Path:
    cfg = tmp_path / "config.json"
    cfg.write_text(
        json.dumps(
            {
                "host": host,
                "port": 0,
                "credentials_path": str(tmp_path / "creds.json"),
                "fetch_ttl_seconds": 30,
                "fetch_timeout_seconds": 5,
                "max_backoff_seconds": 60,
                "log_level": "INFO",
            }
        ),
        encoding="utf-8",
    )
    return cfg


class TestParseArgs:
    def test_required_config(self) -> None:
        with pytest.raises(SystemExit):
            _parse_args([])

    def test_minimum_args(self, tmp_path: Path) -> None:
        ns = _parse_args(["--config", str(tmp_path / "c.json")])
        assert ns.config == tmp_path / "c.json"
        assert ns.debug is False
        assert ns.quiet is False
        assert ns.log_file is None
        assert ns.dryrun is False

    def test_all_flags(self, tmp_path: Path) -> None:
        ns = _parse_args(
            [
                "--config",
                str(tmp_path / "c.json"),
                "--debug",
                "--quiet",
                "--log-file",
                str(tmp_path / "out.log"),
                "--dryrun",
            ]
        )
        assert ns.debug is True
        assert ns.quiet is True
        assert ns.log_file == tmp_path / "out.log"
        assert ns.dryrun is True

    def test_short_quiet(self, tmp_path: Path) -> None:
        ns = _parse_args(["--config", str(tmp_path / "c.json"), "-q"])
        assert ns.quiet is True


class TestResolveLogLevel:
    def test_debug_wins(self) -> None:
        assert (
            _resolve_log_level(settings_level="WARNING", debug=True, quiet=False)
            == logging.DEBUG
        )

    def test_quiet_when_no_debug(self) -> None:
        assert (
            _resolve_log_level(settings_level="INFO", debug=False, quiet=True)
            == logging.WARNING
        )

    def test_settings_value(self) -> None:
        assert (
            _resolve_log_level(settings_level="ERROR", debug=False, quiet=False)
            == logging.ERROR
        )

    def test_unknown_settings_falls_back_to_info(self) -> None:
        assert (
            _resolve_log_level(settings_level="BOGUS", debug=False, quiet=False)
            == logging.INFO
        )


class TestConfigureLogging:
    def test_file_handler_added(self, tmp_path: Path) -> None:
        log_file = tmp_path / "out.log"
        # Reset root logger handlers between tests to avoid leakage.
        root = logging.getLogger()
        original_handlers = list(root.handlers)
        original_excepthook = sys.excepthook
        try:
            for h in original_handlers:
                root.removeHandler(h)
            _configure_logging(level=logging.INFO, log_file=log_file)
            handler_types = {type(h).__name__ for h in root.handlers}
            assert "FileHandler" in handler_types
            assert sys.excepthook is not original_excepthook
        finally:
            for h in list(root.handlers):
                root.removeHandler(h)
            for h in original_handlers:
                root.addHandler(h)
            sys.excepthook = original_excepthook


class TestMain:
    def test_missing_config_exits_error(self, tmp_path: Path, capsys) -> None:
        rc = main(["--config", str(tmp_path / "missing.json")])
        assert rc == EXIT_ERROR
        captured = capsys.readouterr()
        assert "config not found" in captured.err

    def test_dryrun_returns_success(self, tmp_path: Path) -> None:
        cfg = _write_cfg(tmp_path)
        # Reset root handlers + excepthook so test isolation holds.
        root = logging.getLogger()
        original_handlers = list(root.handlers)
        original_excepthook = sys.excepthook
        try:
            for h in original_handlers:
                root.removeHandler(h)
            rc = main(["--config", str(cfg), "--dryrun"])
        finally:
            for h in list(root.handlers):
                root.removeHandler(h)
            for h in original_handlers:
                root.addHandler(h)
            sys.excepthook = original_excepthook
        assert rc == EXIT_SUCCESS

    def test_full_run_serves_then_exits_on_keyboard_interrupt(
        self, tmp_path: Path
    ) -> None:
        cfg = _write_cfg(tmp_path)
        root = logging.getLogger()
        original_handlers = list(root.handlers)
        original_excepthook = sys.excepthook
        with patch("claude_quota_exporter.__main__.build_server") as mock_build:
            mock_server = mock_build.return_value
            mock_server.serve_forever.side_effect = KeyboardInterrupt()
            try:
                for h in original_handlers:
                    root.removeHandler(h)
                rc = main(["--config", str(cfg)])
            finally:
                for h in list(root.handlers):
                    root.removeHandler(h)
                for h in original_handlers:
                    root.addHandler(h)
                sys.excepthook = original_excepthook
        assert rc == EXIT_SUCCESS
        mock_server.serve_forever.assert_called_once()
        mock_server.server_close.assert_called_once()
