# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Tests for fetcher: throttling, backoff, extraction, refresh paths."""

import io
import json
import time
import urllib.error
from pathlib import Path
from unittest.mock import patch

import pytest

from claude_quota_exporter.auth import Credentials
from claude_quota_exporter.fetcher import (
    FetchResult,
    Fetcher,
    _iso_to_epoch_seconds,
    extract_buckets,
    fetch_from_api,
)

SAMPLE_RAW = {
    "five_hour": {
        "utilization": 11.0,
        "resets_at": "2026-04-13T07:00:00+00:00",
    },
    "seven_day": {
        "utilization": 8.0,
        "resets_at": "2026-04-19T13:00:00+00:00",
    },
    "seven_day_opus": {
        "utilization": 4.0,
        "resets_at": "2026-04-19T13:00:00+00:00",
    },
}


def _ok(payload: dict | None = None) -> FetchResult:
    return FetchResult(status=200, payload=payload or SAMPLE_RAW)


def _fail(status: int = 0) -> FetchResult:
    return FetchResult(status=status, payload=None)


class TestIsoToEpoch:
    def test_valid_iso(self) -> None:
        v = _iso_to_epoch_seconds("2026-04-13T07:00:00+00:00")
        assert isinstance(v, float)
        assert v > 0

    @pytest.mark.parametrize("bad", [None, "", "not a date", 123])
    def test_invalid(self, bad: object) -> None:
        assert _iso_to_epoch_seconds(bad) is None


class TestExtractBuckets:
    def test_normalizes_utilization_to_ratio(self) -> None:
        out = extract_buckets(SAMPLE_RAW)
        assert out["five_hour"]["utilization"] == pytest.approx(0.11)
        assert out["seven_day"]["utilization"] == pytest.approx(0.08)
        assert out["seven_day_opus"]["utilization"] == pytest.approx(0.04)

    def test_dynamic_bucket_picked_up(self) -> None:
        raw = {
            "novel_bucket": {
                "utilization": 50.0,
                "resets_at": "2026-04-19T13:00:00+00:00",
            }
        }
        out = extract_buckets(raw)
        assert "novel_bucket" in out
        assert out["novel_bucket"]["utilization"] == pytest.approx(0.5)

    def test_non_dict_top_level_skipped(self) -> None:
        raw = {"meta": "ignore me", "five_hour": SAMPLE_RAW["five_hour"]}
        out = extract_buckets(raw)
        assert "meta" not in out
        assert "five_hour" in out

    def test_null_resets_at(self) -> None:
        raw = {"five_hour": {"utilization": 0.0, "resets_at": None}}
        out = extract_buckets(raw)
        assert out["five_hour"]["utilization"] == 0.0
        assert out["five_hour"]["resets_at"] is None

    def test_missing_utilization_yields_none(self) -> None:
        raw = {"x": {"resets_at": "2026-04-19T13:00:00+00:00"}}
        out = extract_buckets(raw)
        assert out["x"]["utilization"] is None
        assert isinstance(out["x"]["resets_at"], float)


def _make_fetcher(
    tmp_path: Path,
    ttl: int = 120,
    expires_at: float | None = None,
) -> Fetcher:
    creds_path = tmp_path / "creds.json"
    creds_path.write_text(
        json.dumps(
            {
                "claudeAiOauth": {
                    "accessToken": "sk-ant-oat01-AAA",
                    "refreshToken": "sk-ant-ort01-BBB",
                    "expiresAt": int(
                        (expires_at if expires_at is not None else time.time() + 7200)
                        * 1000
                    ),
                }
            }
        ),
        encoding="utf-8",
    )
    return Fetcher(
        credentials_path=creds_path,
        ttl_seconds=ttl,
        timeout_seconds=5,
        max_backoff_seconds=3600,
        refresh_skew_seconds=300,
        refresh_urls=["https://example.invalid/v1/oauth/token"],
        oauth_client_id="cid",
        refresh_user_agent="ua",
    )


class TestFetcherRefresh:
    def test_first_refresh_populates_cache(self, tmp_path: Path) -> None:
        f = _make_fetcher(tmp_path)
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=_ok(),
        ):
            assert f.refresh_if_due() is True
        assert f.cached_raw == SAMPLE_RAW
        assert f.success_count == 1
        assert f.failure_count == 0
        assert f.last_success_at > 0.0

    def test_ttl_blocks_second_refresh(self, tmp_path: Path) -> None:
        f = _make_fetcher(tmp_path, ttl=120)
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=_ok(),
        ) as mock:
            assert f.refresh_if_due() is True
            assert f.refresh_if_due() is False
        assert mock.call_count == 1

    def test_failure_increments_failure_counter(self, tmp_path: Path) -> None:
        f = _make_fetcher(tmp_path)
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=_fail(),
        ):
            assert f.refresh_if_due() is False
        assert f.failure_count == 1
        assert f.success_count == 0
        assert f.cached_raw is None

    def test_backoff_blocks_immediate_retry(self, tmp_path: Path) -> None:
        f = _make_fetcher(tmp_path)
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=_fail(),
        ) as mock:
            assert f.refresh_if_due() is False
            assert f.refresh_if_due() is False
        assert mock.call_count == 1

    def test_missing_creds_at_startup_skips_fetch(self, tmp_path: Path) -> None:
        f = Fetcher(
            credentials_path=tmp_path / "missing.json",
            ttl_seconds=120,
            timeout_seconds=5,
            max_backoff_seconds=3600,
            refresh_skew_seconds=300,
            refresh_urls=["https://example.invalid/v1/oauth/token"],
            oauth_client_id="cid",
            refresh_user_agent="ua",
        )
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=_ok(),
        ) as mock:
            assert f.refresh_if_due() is False
        mock.assert_not_called()
        assert f.has_credentials() is False
        assert f.success_count == 0

    def test_success_after_failure_resets_backoff(self, tmp_path: Path) -> None:
        f = _make_fetcher(tmp_path)
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=_fail(),
        ):
            f.refresh_if_due()
        assert f._consecutive_failures == 1
        f._last_attempt_at = 0.0
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=_ok(),
        ):
            assert f.refresh_if_due() is True
        assert f._consecutive_failures == 0
        assert f.success_count == 1


class TestFetchFromApiResult:
    def test_success_returns_dict_with_status_200(self) -> None:
        class _R:
            def read(self):
                return b'{"five_hour": {"utilization": 1.0}}'

            def __enter__(self):
                return self

            def __exit__(self, *a):
                return False

        with patch(
            "claude_quota_exporter.fetcher.urllib.request.urlopen",
            return_value=_R(),
        ):
            result = fetch_from_api(token="tk", timeout_seconds=5)
        assert isinstance(result, FetchResult)
        assert result.status == 200
        assert result.payload == {"five_hour": {"utilization": 1.0}}

    def test_401_returns_status_401_none_payload(self) -> None:
        def _raise(req, timeout=None):
            raise urllib.error.HTTPError(
                getattr(req, "full_url", "u"),
                401,
                "Unauthorized",
                {},
                io.BytesIO(b""),
            )

        with patch(
            "claude_quota_exporter.fetcher.urllib.request.urlopen",
            side_effect=_raise,
        ):
            result = fetch_from_api(token="tk", timeout_seconds=5)
        assert result.status == 401
        assert result.payload is None

    def test_network_error_returns_status_zero(self) -> None:
        with patch(
            "claude_quota_exporter.fetcher.urllib.request.urlopen",
            side_effect=urllib.error.URLError("down"),
        ):
            result = fetch_from_api(token="tk", timeout_seconds=5)
        assert result.status == 0
        assert result.payload is None


class TestProactiveRefresh:
    def test_fires_when_expiry_within_skew(self, tmp_path: Path) -> None:
        f = _make_fetcher(tmp_path, expires_at=time.time() + 60)
        new_creds = Credentials(
            access_token="rotated-at",
            refresh_token="rotated-rt",
            expires_at=time.time() + 7200,
            issued_at=time.time(),
        )
        with (
            patch(
                "claude_quota_exporter.fetcher.auth.refresh",
                return_value=new_creds,
            ) as mock_refresh,
            patch(
                "claude_quota_exporter.fetcher.fetch_from_api",
                return_value=_ok(),
            ) as mock_fetch,
        ):
            assert f.refresh_if_due() is True
        mock_refresh.assert_called_once()
        assert mock_fetch.call_args.kwargs["token"] == "rotated-at"
        assert f.refresh_success_count == 1
        assert f.last_refresh_at > 0.0

    def test_does_not_fire_when_token_fresh(self, tmp_path: Path) -> None:
        f = _make_fetcher(tmp_path, expires_at=time.time() + 7200)
        with (
            patch(
                "claude_quota_exporter.fetcher.auth.refresh",
            ) as mock_refresh,
            patch(
                "claude_quota_exporter.fetcher.fetch_from_api",
                return_value=_ok(),
            ),
        ):
            assert f.refresh_if_due() is True
        mock_refresh.assert_not_called()
        assert f.refresh_success_count == 0

    def test_refresh_failure_preserves_old_creds_and_increments_counter(
        self, tmp_path: Path
    ) -> None:
        f = _make_fetcher(tmp_path, expires_at=time.time() + 60)
        with (
            patch(
                "claude_quota_exporter.fetcher.auth.refresh",
                return_value=None,
            ),
            patch(
                "claude_quota_exporter.fetcher.fetch_from_api",
                return_value=_ok(),
            ) as mock_fetch,
        ):
            assert f.refresh_if_due() is True
        assert mock_fetch.call_args.kwargs["token"] == "sk-ant-oat01-AAA"
        assert f.refresh_failure_count == 1
        assert f.refresh_success_count == 0

    def test_proactive_refresh_writes_back_when_writable(self, tmp_path: Path) -> None:
        f = _make_fetcher(tmp_path, expires_at=time.time() + 60)
        assert f.credentials_writable is True
        new_creds = Credentials(
            access_token="rotated-at",
            refresh_token="rotated-rt",
            expires_at=time.time() + 7200,
            issued_at=time.time(),
        )
        with (
            patch(
                "claude_quota_exporter.fetcher.auth.refresh",
                return_value=new_creds,
            ),
            patch(
                "claude_quota_exporter.fetcher.fetch_from_api",
                return_value=_ok(),
            ),
        ):
            f.refresh_if_due()
        on_disk = json.loads((tmp_path / "creds.json").read_text(encoding="utf-8"))
        assert on_disk["claudeAiOauth"]["accessToken"] == "rotated-at"
        assert on_disk["claudeAiOauth"]["refreshToken"] == "rotated-rt"


class TestReactive401Refresh:
    def test_fires_when_token_expired_and_no_recent_refresh(
        self, tmp_path: Path
    ) -> None:
        # Token expired 60s ago, no recent refresh; proactive will fire
        # first (also gated by skew), then fetch is OK with new token.
        f = _make_fetcher(tmp_path, expires_at=time.time() - 60)
        f._last_refresh_at = 0.0
        new_creds = Credentials(
            access_token="rotated-at",
            refresh_token="rotated-rt",
            expires_at=time.time() + 7200,
            issued_at=time.time(),
        )
        with (
            patch(
                "claude_quota_exporter.fetcher.auth.refresh",
                return_value=new_creds,
            ) as mock_refresh,
            patch(
                "claude_quota_exporter.fetcher.fetch_from_api",
                side_effect=[_ok()],
            ) as mock_fetch,
        ):
            assert f.refresh_if_due() is True
        # Proactive runs (expiry already in past), fetch succeeds on first try.
        assert mock_refresh.call_count == 1
        assert mock_fetch.call_count == 1
        assert f.refresh_success_count == 1

    def test_reactive_path_on_proactive_skipped_token(self, tmp_path: Path) -> None:
        # Token still appears fresh (expires in 7200s), so proactive doesn't
        # fire. But upstream returns 401 anyway. With token believed fresh,
        # reactive does NOT fire (gate: expiry within skew is False).
        f = _make_fetcher(tmp_path, expires_at=time.time() + 7200)
        with (
            patch(
                "claude_quota_exporter.fetcher.auth.refresh",
            ) as mock_refresh,
            patch(
                "claude_quota_exporter.fetcher.fetch_from_api",
                side_effect=[_fail(status=401)],
            ),
        ):
            assert f.refresh_if_due() is False
        mock_refresh.assert_not_called()
        assert f.failure_count == 1
        assert f.refresh_failure_count == 0

    def test_reactive_skipped_after_recent_proactive_refresh(
        self, tmp_path: Path
    ) -> None:
        # Realistic flow: proactive fires (token within skew), refresh
        # succeeds, fetch with the rotated token STILL returns 401 (rare
        # server-side case). Reactive must NOT fire because refresh would
        # not fix it — refreshed_recently gate triggers.
        f = _make_fetcher(tmp_path, expires_at=time.time() + 60)
        new_creds = Credentials(
            access_token="rotated",
            refresh_token="rt-new",
            expires_at=time.time() + 7200,
            issued_at=time.time(),
        )
        with (
            patch(
                "claude_quota_exporter.fetcher.auth.refresh",
                return_value=new_creds,
            ) as mock_refresh,
            patch(
                "claude_quota_exporter.fetcher.auth.write_back",
                return_value=True,
            ),
            patch(
                "claude_quota_exporter.fetcher.fetch_from_api",
                side_effect=[_fail(status=401)],
            ),
        ):
            assert f.refresh_if_due() is False
        # Exactly one refresh: proactive. Reactive did not fire because
        # we just rotated the token (refreshed_recently=True).
        assert mock_refresh.call_count == 1
        assert f.refresh_success_count == 1
        # The 401 still counts as a fetch failure.
        assert f.failure_count == 1


class TestWriteBackLatch:
    def test_mid_run_write_back_failure_latches_and_does_not_retry(
        self, tmp_path: Path
    ) -> None:
        f = _make_fetcher(tmp_path, expires_at=time.time() + 60)
        assert f.credentials_writable is True
        new_creds = Credentials(
            access_token="rotated-at",
            refresh_token="rotated-rt",
            expires_at=time.time() + 7200,
            issued_at=time.time(),
        )
        write_back_calls = {"count": 0}

        def _fake_write_back(*args, **kwargs):
            write_back_calls["count"] += 1
            return False

        with (
            patch(
                "claude_quota_exporter.fetcher.auth.refresh",
                return_value=new_creds,
            ),
            patch(
                "claude_quota_exporter.fetcher.auth.write_back",
                side_effect=_fake_write_back,
            ),
            patch(
                "claude_quota_exporter.fetcher.fetch_from_api",
                return_value=_ok(),
            ),
        ):
            f.refresh_if_due()
            assert f.credentials_writable is False
            # Force another refresh-eligible cycle.
            f._creds = Credentials(
                access_token="another",
                refresh_token="another-rt",
                expires_at=time.time() + 60,
                issued_at=time.time(),
            )
            f._last_success_at = 0.0
            f._last_refresh_at = 0.0
            f.refresh_if_due()
        assert write_back_calls["count"] == 1
