# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Tests for the HTTP server routes via real socket binding on localhost."""

import json
import threading
from pathlib import Path
from unittest.mock import patch

import pytest
from prometheus_client import CollectorRegistry

from claude_quota_exporter.fetcher import Fetcher
from claude_quota_exporter.metrics import QuotaCollector
from claude_quota_exporter.server import build_server

SAMPLE_RAW = {
    "five_hour": {
        "utilization": 11.0,
        "resets_at": "2026-04-13T07:00:00+00:00",
    }
}


@pytest.fixture
def server_ctx(tmp_path: Path):
    import time as _time

    creds = tmp_path / "creds.json"
    creds.write_text(
        json.dumps(
            {
                "claudeAiOauth": {
                    "accessToken": "sk-ant-oat01-AAA",
                    "refreshToken": "sk-ant-ort01-BBB",
                    "expiresAt": int((_time.time() + 7200) * 1000),
                }
            }
        ),
        encoding="utf-8",
    )
    fetcher = Fetcher(
        credentials_path=creds,
        ttl_seconds=120,
        timeout_seconds=5,
        max_backoff_seconds=3600,
        refresh_skew_seconds=300,
        refresh_urls=["https://example.invalid/v1/oauth/token"],
        oauth_client_id="cid",
        refresh_user_agent="ua",
    )
    registry = CollectorRegistry()
    registry.register(QuotaCollector(fetcher=fetcher))

    server = build_server(
        host="127.0.0.1",
        port=0,
        registry=registry,
        fetcher=fetcher,
    )
    port = server.server_address[1]
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        yield fetcher, port
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=2)


def _get(port: int, path: str) -> tuple[int, str]:
    # Bypass the conftest urllib block by going through the raw socket. The
    # conftest only patches urllib.request.urlopen used by the fetcher.
    import socket

    sock = socket.create_connection(("127.0.0.1", port), timeout=2)
    try:
        sock.sendall(f"GET {path} HTTP/1.0\r\nHost: 127.0.0.1\r\n\r\n".encode())
        chunks: list[bytes] = []
        while True:
            data = sock.recv(4096)
            if not data:
                break
            chunks.append(data)
    finally:
        sock.close()
    payload = b"".join(chunks).decode("utf-8", errors="replace")
    head, _, body = payload.partition("\r\n\r\n")
    status_line = head.split("\r\n", 1)[0]
    status = int(status_line.split(" ", 2)[1])
    return status, body


class TestRoutes:
    def test_healthz_always_ok(self, server_ctx) -> None:
        _, port = server_ctx
        status, body = _get(port, "/healthz")
        assert status == 200
        assert "ok" in body

    def test_readyz_200_when_credentials_loaded_no_fetch_yet(self, server_ctx) -> None:
        fetcher, port = server_ctx
        assert fetcher.has_credentials() is True
        assert fetcher.last_success_at == 0.0
        status, body = _get(port, "/readyz")
        assert status == 200
        assert "ready" in body

    def test_readyz_503_when_no_credentials(self, server_ctx) -> None:
        fetcher, port = server_ctx
        # Force creds to None to simulate cold start.
        fetcher._creds = None
        status, body = _get(port, "/readyz")
        assert status == 503
        assert "not ready" in body

    def test_metrics_endpoint_exposes_gauges(self, server_ctx) -> None:
        from claude_quota_exporter.fetcher import FetchResult

        _, port = server_ctx
        with patch(
            "claude_quota_exporter.fetcher.fetch_from_api",
            return_value=FetchResult(status=200, payload=SAMPLE_RAW),
        ):
            status, body = _get(port, "/metrics")
        assert status == 200
        assert 'claude_quota_utilization{bucket="five_hour"} 0.11' in body

    def test_unknown_path_404(self, server_ctx) -> None:
        _, port = server_ctx
        status, _ = _get(port, "/whatever")
        assert status == 404
