# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Tests for auth.py — Credentials, read_credentials, refresh, write_back."""

import io
import json
import os
import stat
import sys
import time
import urllib.error
from datetime import datetime, timezone
from pathlib import Path
from unittest.mock import patch

import pytest

from claude_quota_exporter.auth import (
    Credentials,
    is_writable,
    read_credentials,
    refresh,
    write_back,
)


def _full_creds_blob(
    access: str = "sk-ant-oat01-AAA",
    refresh_tok: str = "sk-ant-ort01-BBB",
    expires_at_ms: int = 1779580800694,
    extras: dict | None = None,
) -> dict:
    payload = {
        "claudeAiOauth": {
            "accessToken": access,
            "refreshToken": refresh_tok,
            "expiresAt": expires_at_ms,
        }
    }
    if extras:
        payload["claudeAiOauth"].update(extras)
    return payload


class TestReadCredentials:
    def test_happy_path_ms_expires(self, tmp_path: Path) -> None:
        p = tmp_path / "creds.json"
        p.write_text(json.dumps(_full_creds_blob()), encoding="utf-8")
        result = read_credentials(p)
        assert result is not None
        creds, raw = result
        assert isinstance(creds, Credentials)
        assert creds.access_token == "sk-ant-oat01-AAA"
        assert creds.refresh_token == "sk-ant-ort01-BBB"
        assert creds.expires_at == pytest.approx(1779580800.694)
        assert raw["claudeAiOauth"]["accessToken"] == "sk-ant-oat01-AAA"

    def test_iso_string_expires(self, tmp_path: Path) -> None:
        p = tmp_path / "creds.json"
        blob = _full_creds_blob()
        blob["claudeAiOauth"]["expiresAt"] = "2026-04-13T07:00:00+00:00"
        p.write_text(json.dumps(blob), encoding="utf-8")
        result = read_credentials(p)
        assert result is not None
        creds, _ = result
        expected = datetime(2026, 4, 13, 7, 0, 0, tzinfo=timezone.utc).timestamp()
        assert creds.expires_at == pytest.approx(expected)

    def test_preserves_unknown_fields(self, tmp_path: Path) -> None:
        p = tmp_path / "creds.json"
        blob = _full_creds_blob(
            extras={"scopes": ["user:profile"], "subscriptionType": "max"}
        )
        p.write_text(json.dumps(blob), encoding="utf-8")
        result = read_credentials(p)
        assert result is not None
        _, raw = result
        assert raw["claudeAiOauth"]["scopes"] == ["user:profile"]
        assert raw["claudeAiOauth"]["subscriptionType"] == "max"

    def test_missing_file_returns_none(self, tmp_path: Path) -> None:
        assert read_credentials(tmp_path / "nope.json") is None

    def test_malformed_json_returns_none(self, tmp_path: Path) -> None:
        p = tmp_path / "creds.json"
        p.write_text("not json", encoding="utf-8")
        assert read_credentials(p) is None

    def test_missing_claudeAiOauth_block_returns_none(self, tmp_path: Path) -> None:
        p = tmp_path / "creds.json"
        p.write_text(json.dumps({"other": {}}), encoding="utf-8")
        assert read_credentials(p) is None

    @pytest.mark.parametrize(
        "missing_key",
        ["accessToken", "refreshToken", "expiresAt"],
    )
    def test_missing_required_field_returns_none(
        self, tmp_path: Path, missing_key: str
    ) -> None:
        blob = _full_creds_blob()
        del blob["claudeAiOauth"][missing_key]
        p = tmp_path / "creds.json"
        p.write_text(json.dumps(blob), encoding="utf-8")
        assert read_credentials(p) is None

    def test_empty_token_value_returns_none(self, tmp_path: Path) -> None:
        p = tmp_path / "creds.json"
        p.write_text(json.dumps(_full_creds_blob(access="")), encoding="utf-8")
        assert read_credentials(p) is None

    def test_unparseable_expires_at_returns_none(self, tmp_path: Path) -> None:
        blob = _full_creds_blob()
        blob["claudeAiOauth"]["expiresAt"] = "not a date"
        p = tmp_path / "creds.json"
        p.write_text(json.dumps(blob), encoding="utf-8")
        assert read_credentials(p) is None

    def test_directory_path_returns_none(self, tmp_path: Path) -> None:
        # IsADirectoryError is an OSError subclass; must be swallowed.
        assert read_credentials(tmp_path) is None


_DEFAULT_REFRESH_BODY = {
    "access_token": "sk-ant-oat01-NEW",
    "refresh_token": "sk-ant-ort01-NEW",
    "expires_in": 28800,
}


def _fake_urlopen_factory(*, body: dict, status: int = 200):
    """Build a fake urlopen that returns body once."""

    class _Resp:
        def __init__(self, data: bytes) -> None:
            self._data = data

        def read(self) -> bytes:
            return self._data

        def __enter__(self):
            return self

        def __exit__(self, *args):
            return False

    def _fake_urlopen(req, timeout=None):
        if status >= 400:
            raise urllib.error.HTTPError(
                req.full_url,
                status,
                "err",
                {},
                io.BytesIO(json.dumps(body).encode()),
            )
        return _Resp(json.dumps(body).encode())

    return _fake_urlopen


REFRESH_URLS = ["https://example.invalid/v1/oauth/token"]


class TestRefresh:
    def test_happy_path(self) -> None:
        before = time.time()
        with patch(
            "claude_quota_exporter.auth.urllib.request.urlopen",
            side_effect=_fake_urlopen_factory(body=_DEFAULT_REFRESH_BODY),
        ):
            creds = refresh(
                refresh_token="old-refresh",
                urls=REFRESH_URLS,
                client_id="cid",
                user_agent="test-ua",
                timeout_seconds=5,
            )
        assert creds is not None
        assert creds.access_token == "sk-ant-oat01-NEW"
        assert creds.refresh_token == "sk-ant-ort01-NEW"
        assert creds.expires_at >= before + 28799
        assert creds.expires_at <= time.time() + 28800
        assert creds.issued_at >= before

    def test_failover_url1_5xx_url2_200(self) -> None:
        calls: list[str] = []

        def fake(req, timeout=None):
            calls.append(req.full_url)
            if req.full_url == "https://a.invalid/v1/oauth/token":
                raise urllib.error.HTTPError(
                    req.full_url, 503, "err", {}, io.BytesIO(b"{}")
                )
            return _fake_urlopen_factory(body=_DEFAULT_REFRESH_BODY)(req, timeout)

        with patch(
            "claude_quota_exporter.auth.urllib.request.urlopen",
            side_effect=fake,
        ):
            creds = refresh(
                refresh_token="rt",
                urls=[
                    "https://a.invalid/v1/oauth/token",
                    "https://b.invalid/v1/oauth/token",
                ],
                client_id="cid",
                user_agent="test-ua",
                timeout_seconds=5,
            )
        assert creds is not None
        assert calls == [
            "https://a.invalid/v1/oauth/token",
            "https://b.invalid/v1/oauth/token",
        ]

    def test_all_urls_fail_returns_none(self) -> None:
        def fake(req, timeout=None):
            raise urllib.error.URLError("network down")

        with patch(
            "claude_quota_exporter.auth.urllib.request.urlopen",
            side_effect=fake,
        ):
            creds = refresh(
                refresh_token="rt",
                urls=[
                    "https://a.invalid/v1/oauth/token",
                    "https://b.invalid/v1/oauth/token",
                ],
                client_id="cid",
                user_agent="test-ua",
                timeout_seconds=5,
            )
        assert creds is None

    def test_missing_access_token_in_response_returns_none(self) -> None:
        body = {"refresh_token": "rt-new", "expires_in": 3600}
        with patch(
            "claude_quota_exporter.auth.urllib.request.urlopen",
            side_effect=_fake_urlopen_factory(body=body),
        ):
            creds = refresh(
                refresh_token="rt",
                urls=REFRESH_URLS,
                client_id="cid",
                user_agent="test-ua",
                timeout_seconds=5,
            )
        assert creds is None

    def test_missing_refresh_token_reuses_old(self) -> None:
        body = {"access_token": "at-new", "expires_in": 3600}
        with patch(
            "claude_quota_exporter.auth.urllib.request.urlopen",
            side_effect=_fake_urlopen_factory(body=body),
        ):
            creds = refresh(
                refresh_token="old-rt",
                urls=REFRESH_URLS,
                client_id="cid",
                user_agent="test-ua",
                timeout_seconds=5,
            )
        assert creds is not None
        assert creds.refresh_token == "old-rt"

    def test_missing_expires_in_defaults_to_3600(self) -> None:
        body = {"access_token": "at-new", "refresh_token": "rt-new"}
        before = time.time()
        with patch(
            "claude_quota_exporter.auth.urllib.request.urlopen",
            side_effect=_fake_urlopen_factory(body=body),
        ):
            creds = refresh(
                refresh_token="rt",
                urls=REFRESH_URLS,
                client_id="cid",
                user_agent="test-ua",
                timeout_seconds=5,
            )
        assert creds is not None
        assert creds.expires_at >= before + 3599
        assert creds.expires_at <= time.time() + 3600

    def test_non_json_body_returns_none(self) -> None:
        class _Resp:
            def read(self) -> bytes:
                return b"<html>oops</html>"

            def __enter__(self):
                return self

            def __exit__(self, *args):
                return False

        with patch(
            "claude_quota_exporter.auth.urllib.request.urlopen",
            return_value=_Resp(),
        ):
            creds = refresh(
                refresh_token="rt",
                urls=REFRESH_URLS,
                client_id="cid",
                user_agent="test-ua",
                timeout_seconds=5,
            )
        assert creds is None

    def test_request_body_and_headers(self) -> None:
        captured: dict = {}

        def fake(req, timeout=None):
            captured["url"] = req.full_url
            captured["method"] = req.get_method()
            captured["headers"] = dict(req.header_items())
            captured["body"] = json.loads(req.data.decode())
            return _fake_urlopen_factory(body=_DEFAULT_REFRESH_BODY)(req, timeout)

        with patch(
            "claude_quota_exporter.auth.urllib.request.urlopen",
            side_effect=fake,
        ):
            refresh(
                refresh_token="rt-stored",
                urls=REFRESH_URLS,
                client_id="my-client-id",
                user_agent="my-ua/1.0",
                timeout_seconds=5,
            )
        assert captured["url"] == REFRESH_URLS[0]
        assert captured["method"] == "POST"
        assert captured["body"] == {
            "grant_type": "refresh_token",
            "refresh_token": "rt-stored",
            "client_id": "my-client-id",
        }
        ua = {k.lower(): v for k, v in captured["headers"].items()}
        assert ua.get("user-agent") == "my-ua/1.0"
        assert ua.get("content-type") == "application/json"


class TestIsWritable:
    def test_true_for_writable_path(self, tmp_path: Path) -> None:
        target = tmp_path / "creds.json"
        target.write_text("{}", encoding="utf-8")
        assert is_writable(target) is True

    def test_true_when_file_missing_but_dir_writable(self, tmp_path: Path) -> None:
        assert is_writable(tmp_path / "future.json") is True

    @pytest.mark.skipif(
        sys.platform.startswith("win"),
        reason="POSIX permission semantics",
    )
    def test_false_for_readonly_dir(self, tmp_path: Path) -> None:
        ro_dir = tmp_path / "ro"
        ro_dir.mkdir()
        target = ro_dir / "creds.json"
        target.write_text("{}", encoding="utf-8")
        os.chmod(ro_dir, stat.S_IRUSR | stat.S_IXUSR)
        try:
            assert is_writable(target) is False
        finally:
            os.chmod(ro_dir, stat.S_IRWXU)


class TestWriteBack:
    def test_happy_path_preserves_unknown_fields(self, tmp_path: Path) -> None:
        path = tmp_path / "creds.json"
        original = {
            "claudeAiOauth": {
                "accessToken": "old-at",
                "refreshToken": "old-rt",
                "expiresAt": 100,
                "scopes": ["user:profile"],
            },
            "topLevelExtra": "preserved",
        }
        path.write_text(json.dumps(original), encoding="utf-8")
        new_creds = Credentials(
            access_token="new-at",
            refresh_token="new-rt",
            expires_at=1779580800.0,
            issued_at=time.time(),
        )
        assert write_back(path, new_creds, original) is True
        on_disk = json.loads(path.read_text(encoding="utf-8"))
        assert on_disk["claudeAiOauth"]["accessToken"] == "new-at"
        assert on_disk["claudeAiOauth"]["refreshToken"] == "new-rt"
        assert on_disk["claudeAiOauth"]["expiresAt"] == 1779580800000
        assert on_disk["claudeAiOauth"]["scopes"] == ["user:profile"]
        assert on_disk["topLevelExtra"] == "preserved"

    def test_atomic_via_temp_file(self, tmp_path: Path) -> None:
        path = tmp_path / "creds.json"
        path.write_text("{}", encoding="utf-8")
        creds = Credentials(
            access_token="at",
            refresh_token="rt",
            expires_at=0.0,
            issued_at=time.time(),
        )
        assert write_back(path, creds, {}) is True
        siblings = sorted(p.name for p in tmp_path.iterdir())
        assert "creds.json" in siblings
        assert not any(name.endswith(".tmp") for name in siblings)

    @pytest.mark.skipif(
        sys.platform.startswith("win"),
        reason="POSIX mode semantics",
    )
    def test_preserves_source_file_mode(self, tmp_path: Path) -> None:
        path = tmp_path / "creds.json"
        path.write_text("{}", encoding="utf-8")
        os.chmod(path, 0o600)
        creds = Credentials(
            access_token="at",
            refresh_token="rt",
            expires_at=0.0,
            issued_at=time.time(),
        )
        assert write_back(path, creds, {}) is True
        mode = stat.S_IMODE(path.stat().st_mode)
        assert mode == 0o600

    def test_returns_false_when_source_missing(self, tmp_path: Path) -> None:
        creds = Credentials(
            access_token="at",
            refresh_token="rt",
            expires_at=0.0,
            issued_at=time.time(),
        )
        assert write_back(tmp_path / "nope.json", creds, {}) is False
