#!/usr/bin/env sh
# Generated By: Claude Code (Claude Opus 4.7 (1M context))
#
# Mints a long-lived OAuth bearer token via `claude setup-token` and
# writes a credentials.json the exporter consumes.
#
# The expiresAt field is set to mint-time + TTL_DAYS so operators can
# alert on `claude_quota_access_token_expires_at_seconds` approaching
# `now`. Anthropic's setup-token issues a token "valid for 1 year"; the
# default TTL_DAYS=365 matches.
#
# Usage:
#   ./scripts/mint-creds.sh                            # default: ./mint/.credentials.json, 365d TTL
#   OUT=/path/to/creds.json ./scripts/mint-creds.sh
#   TTL_DAYS=180 ./scripts/mint-creds.sh
#
# Requires: claude CLI installed and able to setup-token (active Pro/Max
# subscription).

set -eu

OUT="${OUT:-./mint/.credentials.json}"
TTL_DAYS="${TTL_DAYS:-365}"

mkdir -p "$(dirname "$OUT")"

# The setup-token flow is interactive (opens a URL in your browser;
# you paste the returned code back into the terminal). The grep+sed
# extracts the sk-ant-oat01- token from the success output.
TOKEN=$(claude setup-token 2>&1 | grep sk-ant-oat01 | sed 's/[[:space:]]//g')

if [ -z "$TOKEN" ]; then
    echo "mint-creds: no sk-ant-oat01-* token in setup-token output" >&2
    exit 1
fi

EXPIRES_AT_MS=$(( $(date +%s) * 1000 + TTL_DAYS * 86400 * 1000 ))

cat > "$OUT" <<EOF
{
  "claudeAiOauth": {
    "accessToken": "$TOKEN",
    "expiresAt": $EXPIRES_AT_MS
  }
}
EOF

chmod 600 "$OUT" 2>/dev/null || true

EXPIRES_HUMAN=$(date -d "@$((EXPIRES_AT_MS / 1000))" -Iseconds 2>/dev/null || echo "$EXPIRES_AT_MS ms")
echo "Wrote $OUT"
echo "  expires_at = $EXPIRES_HUMAN"
echo "  ttl_days   = $TTL_DAYS"
echo ""
echo "Use it via: make run-image CREDS_FILE=$OUT"
