# Generated By: Claude Code (Claude Opus 4.7 (1M context))
.PHONY: test-unit test-coverage test-format test-lint test-typecheck test-complexity

test-unit: install-dev  ## Run pytest
	$(PYTHON) -m pytest

test-coverage: install-dev  ## Run pytest with 80% coverage threshold
	$(PYTHON) -m pytest --cov=$(SRC_DIR) --cov-report=term --cov-fail-under=80

test-format: install-dev  ## Check formatting (exits non-zero if changes needed)
	$(PYTHON) -m black --check $(SRC_DIR) tests

test-lint: install-dev  ## Lint with flake8
	$(PYTHON) -m flake8 --max-line-length=88 --extend-ignore=E203,W503 $(SRC_DIR) tests

test-typecheck: install-dev  ## Type check with mypy
	$(PYTHON) -m mypy $(SRC_DIR)

test-complexity: install-dev  ## Cyclomatic complexity check (xenon)
	$(PYTHON) -m xenon $(SRC_DIR) --max-absolute B --max-modules B --max-average A
