# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""CLI entry point."""

import argparse
import logging
import sys
from pathlib import Path

from prometheus_client import CollectorRegistry

from claude_quota_exporter import __version__
from claude_quota_exporter.config import Settings
from claude_quota_exporter.fetcher import Fetcher
from claude_quota_exporter.metrics import QuotaCollector
from claude_quota_exporter.server import build_server

EXIT_SUCCESS = 0
EXIT_ERROR = 1


def _parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="claude-quota-exporter",
        description="Prometheus exporter for Claude OAuth API usage limits.",
    )
    parser.add_argument(
        "--config",
        type=Path,
        required=True,
        help="path to JSON config file",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="enable debug output",
    )
    parser.add_argument(
        "--quiet",
        "-q",
        action="store_true",
        help="suppress non-essential output",
    )
    parser.add_argument(
        "--log-file",
        type=Path,
        default=None,
        help="write log output to file (append mode)",
    )
    parser.add_argument(
        "--dryrun",
        action="store_true",
        help="validate config and report planned listener without binding",
    )
    parser.add_argument(
        "--version", action="version", version=f"%(prog)s {__version__}"
    )
    return parser.parse_args(argv)


def _resolve_log_level(*, settings_level: str, debug: bool, quiet: bool) -> int:
    if debug:
        return logging.DEBUG
    if quiet:
        return logging.WARNING
    return logging.getLevelNamesMapping().get(settings_level.upper(), logging.INFO)


def _configure_logging(*, level: int, log_file: Path | None) -> None:
    handlers: list[logging.Handler] = [logging.StreamHandler(stream=sys.stderr)]
    if log_file is not None:
        resolved = log_file.expanduser().resolve()
        handlers.append(logging.FileHandler(resolved, mode="a", encoding="utf-8"))
    logging.basicConfig(
        level=level,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
        handlers=handlers,
    )

    def _excepthook(exc_type, exc, tb):  # type: ignore[no-untyped-def]
        logging.getLogger(__name__).error(
            "uncaught exception", exc_info=(exc_type, exc, tb)
        )

    sys.excepthook = _excepthook


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv if argv is not None else sys.argv[1:])

    try:
        settings = Settings.from_config(config_path=args.config)
    except FileNotFoundError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return EXIT_ERROR

    level = _resolve_log_level(
        settings_level=settings.log_level, debug=args.debug, quiet=args.quiet
    )
    _configure_logging(level=level, log_file=args.log_file)
    logger = logging.getLogger(__name__)

    fetcher = Fetcher(
        credentials_path=settings.credentials_path,
        ttl_seconds=settings.fetch_ttl_seconds,
        timeout_seconds=settings.fetch_timeout_seconds,
        max_backoff_seconds=settings.max_backoff_seconds,
        refresh_skew_seconds=settings.refresh_skew_seconds,
        refresh_urls=settings.refresh_urls,
        oauth_client_id=settings.oauth_client_id,
        refresh_user_agent=settings.refresh_user_agent,
    )
    registry = CollectorRegistry()
    registry.register(QuotaCollector(fetcher=fetcher))

    if args.dryrun:
        logger.info(
            "dryrun: would listen on %s:%d (credentials=%s, ttl=%ds)",
            settings.host,
            settings.port,
            settings.credentials_path,
            settings.fetch_ttl_seconds,
        )
        return EXIT_SUCCESS

    server = build_server(
        host=settings.host,
        port=settings.port,
        registry=registry,
        fetcher=fetcher,
    )
    logger.info(
        "claude-quota-exporter %s listening on %s:%d",
        __version__,
        settings.host,
        settings.port,
    )
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        logger.info("shutdown requested")
    finally:
        server.server_close()
    return EXIT_SUCCESS


if __name__ == "__main__":
    sys.exit(main())
