# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Credentials I/O for claude-quota-exporter.

Reads a bearer-token JSON from disk. The fetcher invokes this on every
quota-fetch attempt so an external rotator (whatever updates the mounted
Secret / file) can replace the token without a pod restart. See
CLAUDE.md.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class Credentials:
    """Snapshot of the OAuth bearer in memory."""

    access_token: str


def read_credentials(path: Path) -> Credentials | None:
    """Parse credentials from disk.

    Required field: ``claudeAiOauth.accessToken`` (non-empty string).
    Returns ``None`` for any failure (missing file, malformed JSON,
    missing/empty access token). Logs the specific failure at WARNING.
    Never raises.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        logger.warning("credentials file not found: %s", path)
        return None
    except IsADirectoryError:
        logger.warning("credentials path is a directory, expected a file: %s", path)
        return None
    except PermissionError:
        logger.warning("credentials file not readable (permission denied): %s", path)
        return None
    except OSError as exc:
        logger.warning("credentials file unreadable: %s (%s)", path, exc)
        return None
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        logger.warning("credentials file is not valid JSON: %s (%s)", path, exc)
        return None
    if not isinstance(data, dict):
        logger.warning("credentials file is not a JSON object: %s", path)
        return None
    section = data.get("claudeAiOauth")
    if not isinstance(section, dict):
        logger.warning("credentials file missing claudeAiOauth block: %s", path)
        return None
    access = section.get("accessToken")
    if not isinstance(access, str) or not access:
        logger.warning(
            "credentials file has missing/empty claudeAiOauth.accessToken: %s",
            path,
        )
        return None
    return Credentials(access_token=access)
