# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Credentials I/O and OAuth refresh primitives for claude-quota-exporter.

Pure-function module. State and locking live in Fetcher.
"""

from __future__ import annotations

import json
import logging
import os
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)

DEFAULT_EXPIRES_IN_SECONDS = 3600


@dataclass(frozen=True)
class Credentials:
    """Snapshot of OAuth credentials in memory.

    `expires_at` and `issued_at` are Unix epoch seconds (float).
    Disk format uses milliseconds — converted at the boundary.
    """

    access_token: str
    refresh_token: str
    expires_at: float
    issued_at: float


def _parse_expires_at(value: object) -> float | None:
    """Accept ms-int (Claude Code) or ISO-8601 string. Return epoch seconds."""
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        return float(value) / 1000.0
    if isinstance(value, str) and value:
        try:
            return datetime.fromisoformat(value).timestamp()
        except (ValueError, TypeError):  # fmt: skip
            return None
    return None


def read_credentials(path: Path) -> tuple[Credentials, dict] | None:
    """Parse credentials from disk.

    Returns (Credentials, raw_dict) on success. The raw dict is the full
    parsed JSON — used at write-back time to preserve unknown sibling
    fields. Returns None for any failure (missing file, malformed JSON,
    missing/empty required fields, unparseable expiresAt). Logs the
    specific failure reason at WARNING. Never raises.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        logger.warning("credentials file not found: %s", path)
        return None
    except IsADirectoryError:
        logger.warning("credentials path is a directory, expected a file: %s", path)
        return None
    except PermissionError:
        logger.warning("credentials file not readable (permission denied): %s", path)
        return None
    except OSError as exc:
        logger.warning("credentials file unreadable: %s (%s)", path, exc)
        return None
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        logger.warning("credentials file is not valid JSON: %s (%s)", path, exc)
        return None
    if not isinstance(data, dict):
        logger.warning("credentials file is not a JSON object: %s", path)
        return None
    section = data.get("claudeAiOauth")
    if not isinstance(section, dict):
        logger.warning("credentials file missing claudeAiOauth block: %s", path)
        return None
    access = section.get("accessToken")
    if not isinstance(access, str) or not access:
        logger.warning(
            "credentials file has missing/empty claudeAiOauth.accessToken: %s",
            path,
        )
        return None
    refresh_tok = section.get("refreshToken")
    if not isinstance(refresh_tok, str) or not refresh_tok:
        logger.warning(
            "credentials file has missing/empty claudeAiOauth.refreshToken: %s",
            path,
        )
        return None
    expires_at = _parse_expires_at(section.get("expiresAt"))
    if expires_at is None:
        logger.warning(
            "credentials file has missing/unparseable claudeAiOauth.expiresAt: %s",
            path,
        )
        return None
    creds = Credentials(
        access_token=access,
        refresh_token=refresh_tok,
        expires_at=expires_at,
        issued_at=time.time(),
    )
    return creds, data


def _extract_oauth_error(exc: urllib.error.HTTPError) -> str:
    """Pull the RFC-6749 `error` field from an HTTPError body if present."""
    try:
        raw = exc.read()
    except Exception:  # noqa: BLE001 — body read is best-effort
        return "unknown"
    try:
        body = json.loads(raw)
    except (json.JSONDecodeError, TypeError):  # fmt: skip
        return "unknown"
    if isinstance(body, dict):
        code = body.get("error")
        if isinstance(code, str) and code:
            return code
    return "unknown"


def refresh(
    *,
    refresh_token: str,
    urls: list[str],
    client_id: str,
    user_agent: str,
    timeout_seconds: int,
) -> Credentials | None:
    """Exchange `refresh_token` for a new credential set.

    Tries each URL in order. Returns a Credentials snapshot on the first
    success. Returns None when every URL fails (network error, non-2xx,
    non-JSON body, or 2xx with no `access_token`). Never raises.
    """
    body = json.dumps(
        {
            "grant_type": "refresh_token",
            "refresh_token": refresh_token,
            "client_id": client_id,
        }
    ).encode("utf-8")
    headers = {
        "Content-Type": "application/json",
        "User-Agent": user_agent,
    }
    for url in urls:
        req = urllib.request.Request(url, data=body, headers=headers, method="POST")
        try:
            with urllib.request.urlopen(req, timeout=timeout_seconds) as resp:
                payload = json.loads(resp.read())
        except urllib.error.HTTPError as exc:
            error_code = _extract_oauth_error(exc)
            logger.warning(
                "oauth refresh failed url=%s status=%d error=%s",
                url,
                exc.code,
                error_code,
            )
            continue
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError):  # fmt: skip
            logger.warning("oauth refresh failed url=%s error=unknown", url)
            continue
        if not isinstance(payload, dict):
            logger.warning("oauth refresh failed url=%s error=non_dict_body", url)
            continue
        access = payload.get("access_token")
        if not isinstance(access, str) or not access:
            logger.warning(
                "oauth refresh failed url=%s error=missing_access_token", url
            )
            continue
        new_refresh = payload.get("refresh_token")
        if not isinstance(new_refresh, str) or not new_refresh:
            new_refresh = refresh_token
        expires_in_raw = payload.get("expires_in", DEFAULT_EXPIRES_IN_SECONDS)
        try:
            expires_in = float(expires_in_raw)
        except (TypeError, ValueError):  # fmt: skip
            expires_in = float(DEFAULT_EXPIRES_IN_SECONDS)
        now = time.time()
        logger.info("oauth refresh succeeded url=%s", url)
        return Credentials(
            access_token=access,
            refresh_token=new_refresh,
            expires_at=now + expires_in,
            issued_at=now,
        )
    return None


def is_writable(path: Path) -> bool:
    """Probe whether we could later atomically rewrite `path`.

    Creates and deletes a sibling temp file. Returns True if both
    succeed. The probe does not modify or read the target file.
    """
    probe = path.with_suffix(path.suffix + ".write_probe")
    try:
        probe.write_bytes(b"")
        probe.unlink()
        return True
    except OSError:
        return False


def write_back(path: Path, creds: Credentials, raw_dict: dict) -> bool:
    """Atomically write the credentials back to disk.

    Updates only the three fields we own
    (accessToken/refreshToken/expiresAt) inside claudeAiOauth; preserves
    every sibling field. Writes to a temp file in the same directory,
    fsyncs, os.replaces over the original, and re-applies the source
    file mode. Never raises. Returns True on success, False on any
    failure.
    """
    section = raw_dict.setdefault("claudeAiOauth", {})
    if not isinstance(section, dict):
        return False
    section["accessToken"] = creds.access_token
    section["refreshToken"] = creds.refresh_token
    section["expiresAt"] = int(creds.expires_at * 1000)
    try:
        src_mode = path.stat().st_mode & 0o777
    except OSError:
        return False
    tmp = path.with_suffix(path.suffix + ".tmp")
    try:
        with tmp.open("w", encoding="utf-8") as f:
            json.dump(raw_dict, f, indent=2)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, path)
    except OSError:
        try:
            tmp.unlink()
        except OSError:
            pass
        return False
    try:
        os.chmod(path, src_mode)
    except OSError:
        pass  # Windows; non-fatal
    return True
