# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Configuration loader. Loads exclusively from a JSON config file."""

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path

logger = logging.getLogger(__name__)

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 9180
DEFAULT_CREDENTIALS_PATH = Path("/var/run/claude/credentials.json")
DEFAULT_FETCH_TTL_SECONDS = 120
DEFAULT_FETCH_TIMEOUT_SECONDS = 10
DEFAULT_MAX_BACKOFF_SECONDS = 3600
DEFAULT_LOG_LEVEL = "INFO"


@dataclass
class Settings:
    """Exporter service settings."""

    host: str = DEFAULT_HOST
    port: int = DEFAULT_PORT
    credentials_path: Path = field(default_factory=lambda: DEFAULT_CREDENTIALS_PATH)
    fetch_ttl_seconds: int = DEFAULT_FETCH_TTL_SECONDS
    fetch_timeout_seconds: int = DEFAULT_FETCH_TIMEOUT_SECONDS
    max_backoff_seconds: int = DEFAULT_MAX_BACKOFF_SECONDS
    log_level: str = DEFAULT_LOG_LEVEL

    @classmethod
    def from_config(cls, *, config_path: Path) -> "Settings":
        """Load settings from a JSON config file.

        Raises FileNotFoundError if the file does not exist.
        """
        resolved = config_path.expanduser()
        if not resolved.exists():
            raise FileNotFoundError(f"config not found: {resolved}")

        data: dict = {}
        try:
            raw = json.loads(resolved.read_text(encoding="utf-8"))
            if isinstance(raw, dict):
                data = raw
        except json.JSONDecodeError:
            logger.warning("Malformed config file: %s", resolved)

        creds_str = data.get("credentials_path")
        credentials_path = (
            Path(creds_str).expanduser() if creds_str else DEFAULT_CREDENTIALS_PATH
        )

        return cls(
            host=str(data.get("host", DEFAULT_HOST)),
            port=int(data.get("port", DEFAULT_PORT)),
            credentials_path=credentials_path,
            fetch_ttl_seconds=int(
                data.get("fetch_ttl_seconds", DEFAULT_FETCH_TTL_SECONDS)
            ),
            fetch_timeout_seconds=int(
                data.get("fetch_timeout_seconds", DEFAULT_FETCH_TIMEOUT_SECONDS)
            ),
            max_backoff_seconds=int(
                data.get("max_backoff_seconds", DEFAULT_MAX_BACKOFF_SECONDS)
            ),
            log_level=str(data.get("log_level", DEFAULT_LOG_LEVEL)).upper(),
        )
