# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Fetch Claude OAuth usage limits from the Anthropic API.

Self-throttling: TTL gates how often a fetch attempt is made; exponential
backoff suppresses retries after consecutive failures. Cache the last
successful response in memory; the exporter scrape path reads the cache.

The bearer token is read from a credentials JSON file once at startup.
There is no token-refresh flow — rotation is an external concern
(see CLAUDE.md). Operators alert on rising fetch_failure_total.
"""

import json
import logging
import threading
import time
import urllib.error
import urllib.request
from datetime import datetime
from pathlib import Path

from claude_quota_exporter import auth
from claude_quota_exporter.auth import Credentials

logger = logging.getLogger(__name__)

API_URL = "https://api.anthropic.com/api/oauth/usage"
ANTHROPIC_BETA = "oauth-2025-04-20"


def _iso_to_epoch_seconds(value: object) -> float | None:
    """Parse an ISO-8601 datetime string to Unix epoch seconds."""
    if not isinstance(value, str) or not value:
        return None
    try:
        return datetime.fromisoformat(value).timestamp()
    except (ValueError, TypeError):  # fmt: skip
        return None


def extract_buckets(raw: dict) -> dict[str, dict[str, float | None]]:
    """Extract every bucket from the raw API response.

    A bucket is any top-level dict value containing ``utilization`` and
    ``resets_at``. Utilization is normalized from the API's 0..100 scale
    to a 0..1 ratio. resets_at is normalized from ISO-8601 to epoch
    seconds.
    """
    out: dict[str, dict[str, float | None]] = {}
    for name, value in raw.items():
        if not isinstance(value, dict):
            continue
        if "utilization" not in value and "resets_at" not in value:
            continue
        util_raw = value.get("utilization")
        util = float(util_raw) / 100.0 if isinstance(util_raw, (int, float)) else None
        out[name] = {
            "utilization": util,
            "resets_at": _iso_to_epoch_seconds(value.get("resets_at")),
        }
    return out


def fetch_from_api(*, token: str, timeout_seconds: int) -> dict | None:
    """Perform the upstream API call. Return parsed dict or None on failure."""
    req = urllib.request.Request(
        API_URL,
        headers={
            "Authorization": f"Bearer {token}",
            "anthropic-beta": ANTHROPIC_BETA,
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout_seconds) as resp:
            data = json.loads(resp.read())
    except (
        urllib.error.URLError,
        TimeoutError,
        json.JSONDecodeError,
    ) as exc:
        logger.warning("limits API fetch failed: %s", exc)
        return None
    if isinstance(data, dict):
        return data
    return None


class Fetcher:
    """Throttled fetcher with in-memory cache."""

    def __init__(
        self,
        *,
        credentials_path: Path,
        ttl_seconds: int,
        timeout_seconds: int,
        max_backoff_seconds: int,
    ) -> None:
        self._credentials_path = credentials_path
        self._ttl_seconds = ttl_seconds
        self._timeout_seconds = timeout_seconds
        self._max_backoff_seconds = max_backoff_seconds
        self._lock = threading.Lock()
        self._last_success_at: float = 0.0
        self._last_attempt_at: float = 0.0
        self._consecutive_failures: int = 0
        self._success_count: int = 0
        self._failure_count: int = 0
        self._cached_raw: dict | None = None
        self._creds: Credentials | None = auth.read_credentials(credentials_path)
        if self._creds is None:
            logger.error(
                "credentials_path not loadable at startup: %s "
                "(see preceding WARNING for the specific reason); "
                "fetch disabled until process restart",
                credentials_path,
            )
        self._no_creds_logged: bool = False

    @property
    def last_success_at(self) -> float:
        return self._last_success_at

    @property
    def success_count(self) -> int:
        return self._success_count

    @property
    def failure_count(self) -> int:
        return self._failure_count

    @property
    def cached_raw(self) -> dict | None:
        return self._cached_raw

    def has_credentials(self) -> bool:
        return self._creds is not None

    def _backoff_seconds(self) -> float:
        if self._consecutive_failures == 0:
            return 0.0
        return float(
            min(
                (2**self._consecutive_failures) * self._ttl_seconds,
                self._max_backoff_seconds,
            )
        )

    def _is_due(self, *, now: float) -> bool:
        if self._last_success_at == 0.0:
            base_due = True
        else:
            base_due = (now - self._last_success_at) >= self._ttl_seconds
        if not base_due:
            return False
        if self._consecutive_failures > 0:
            cooldown = self._backoff_seconds()
            if (now - self._last_attempt_at) < cooldown:
                return False
        return True

    def refresh_if_due(self) -> bool:
        """Attempt a fetch if TTL elapsed and not in backoff cooldown.

        Returns True on a successful fetch, False otherwise (not due,
        no credentials, or upstream failure).
        """
        with self._lock:
            now = time.time()
            if not self._is_due(now=now):
                return False
            if self._creds is None:
                if not self._no_creds_logged:
                    logger.warning(
                        "credentials not loaded; skipping fetch. "
                        "credentials_path=%s",
                        self._credentials_path,
                    )
                    self._no_creds_logged = True
                return False
            self._last_attempt_at = now
            raw = fetch_from_api(
                token=self._creds.access_token,
                timeout_seconds=self._timeout_seconds,
            )
            if raw is None:
                self._consecutive_failures += 1
                self._failure_count += 1
                logger.warning(
                    "limits fetch failed attempts=%d backoff=%.0fs",
                    self._consecutive_failures,
                    self._backoff_seconds(),
                )
                return False
            self._cached_raw = raw
            self._last_success_at = time.time()
            self._consecutive_failures = 0
            self._success_count += 1
            logger.info("limits fetched and cached")
            return True
