# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""Prometheus metric definitions and exposition.

Metrics are sourced from the Fetcher cache on each /metrics scrape via a
custom Collector. This guarantees /metrics never reports stale gauges
relative to the cache without an explicit reset step.
"""

from typing import Iterable

from prometheus_client.core import (
    CounterMetricFamily,
    GaugeMetricFamily,
    Metric,
)
from prometheus_client.registry import Collector

from claude_quota_exporter.fetcher import Fetcher, extract_buckets


class QuotaCollector(Collector):
    """Emit Claude quota metrics from the Fetcher cache."""

    def __init__(self, *, fetcher: Fetcher) -> None:
        self._fetcher = fetcher

    def collect(self) -> Iterable[Metric]:
        # Force a refresh attempt at scrape time. Throttle inside Fetcher.
        self._fetcher.refresh_if_due()

        utilization = GaugeMetricFamily(
            "claude_quota_utilization",
            "Claude OAuth quota utilization ratio (0..1) per bucket",
            labels=["bucket"],
        )
        resets_at = GaugeMetricFamily(
            "claude_quota_resets_at_seconds",
            "Unix epoch seconds when the bucket resets",
            labels=["bucket"],
        )

        raw = self._fetcher.cached_raw
        if raw is not None:
            for bucket_name, fields in extract_buckets(raw).items():
                util = fields.get("utilization")
                if util is not None:
                    utilization.add_metric([bucket_name], util)
                resets = fields.get("resets_at")
                if resets is not None:
                    resets_at.add_metric([bucket_name], resets)

        yield utilization
        yield resets_at

        success = CounterMetricFamily(
            "claude_quota_fetch_success",
            "Number of successful upstream fetches since process start",
        )
        success.add_metric([], float(self._fetcher.success_count))
        yield success

        failure = CounterMetricFamily(
            "claude_quota_fetch_failure",
            "Number of failed upstream fetches since process start",
        )
        failure.add_metric([], float(self._fetcher.failure_count))
        yield failure

        last_fetch = GaugeMetricFamily(
            "claude_quota_last_fetch_timestamp_seconds",
            "Unix epoch seconds of the last successful upstream fetch",
        )
        last_fetch.add_metric([], self._fetcher.last_success_at)
        yield last_fetch

        access_expiry = GaugeMetricFamily(
            "claude_quota_access_token_expires_at_seconds",
            "Unix epoch seconds when the current OAuth access token expires",
        )
        token_expiry = self._fetcher.access_token_expires_at
        if token_expiry is not None:
            access_expiry.add_metric([], token_expiry)
        yield access_expiry

        refresh_issued = GaugeMetricFamily(
            "claude_quota_refresh_token_issued_at_seconds",
            (
                "Unix epoch seconds when the current refresh token was "
                "first observed locally"
            ),
        )
        rt_issued = self._fetcher.refresh_token_issued_at
        if rt_issued is not None:
            refresh_issued.add_metric([], rt_issued)
        yield refresh_issued

        last_refresh = GaugeMetricFamily(
            "claude_quota_last_refresh_timestamp_seconds",
            "Unix epoch seconds of the last successful OAuth refresh",
        )
        last_refresh.add_metric([], self._fetcher.last_refresh_at)
        yield last_refresh

        creds_present = GaugeMetricFamily(
            "claude_quota_credentials_present",
            "1 if a valid credentials file is loaded, else 0",
        )
        creds_present.add_metric([], 1.0 if self._fetcher.has_credentials() else 0.0)
        yield creds_present

        creds_writable = GaugeMetricFamily(
            "claude_quota_credentials_writable",
            "1 if the credentials file is writable for token rotation, else 0",
        )
        creds_writable.add_metric(
            [], 1.0 if self._fetcher.credentials_writable else 0.0
        )
        yield creds_writable

        refresh_success = CounterMetricFamily(
            "claude_quota_refresh_success",
            "Number of successful OAuth refreshes since process start",
        )
        refresh_success.add_metric([], float(self._fetcher.refresh_success_count))
        yield refresh_success

        refresh_failure = CounterMetricFamily(
            "claude_quota_refresh_failure",
            "Number of failed OAuth refreshes since process start",
        )
        refresh_failure.add_metric([], float(self._fetcher.refresh_failure_count))
        yield refresh_failure
