# Generated By: Claude Code (Claude Opus 4.7 (1M context))
"""HTTP server. Exposes GET /metrics, /healthz, /readyz only."""

import logging
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Type

from prometheus_client import CollectorRegistry, generate_latest
from prometheus_client.exposition import CONTENT_TYPE_LATEST

from claude_quota_exporter.fetcher import Fetcher

logger = logging.getLogger(__name__)


def _build_handler(
    *, registry: CollectorRegistry, fetcher: Fetcher
) -> Type[BaseHTTPRequestHandler]:
    """Construct a handler class closed over the shared registry/fetcher."""

    class Handler(BaseHTTPRequestHandler):
        def _send(self, *, status: int, body: bytes, content_type: str) -> None:
            self.send_response(status)
            self.send_header("Content-Type", content_type)
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def do_GET(self) -> None:  # noqa: N802 (stdlib API)
            if self.path == "/metrics":
                body = generate_latest(registry)
                self._send(status=200, body=body, content_type=CONTENT_TYPE_LATEST)
                return
            if self.path == "/healthz":
                self._send(status=200, body=b"ok\n", content_type="text/plain")
                return
            if self.path == "/readyz":
                if fetcher.has_credentials():
                    self._send(
                        status=200,
                        body=b"ready\n",
                        content_type="text/plain",
                    )
                else:
                    self._send(
                        status=503,
                        body=b"not ready\n",
                        content_type="text/plain",
                    )
                return
            self._send(status=404, body=b"not found\n", content_type="text/plain")

        def log_message(self, format: str, *args: object) -> None:
            logger.info("%s - %s", self.address_string(), format % args)

    return Handler


def build_server(
    *,
    host: str,
    port: int,
    registry: CollectorRegistry,
    fetcher: Fetcher,
) -> ThreadingHTTPServer:
    """Build a ThreadingHTTPServer bound to host:port."""
    handler_cls = _build_handler(registry=registry, fetcher=fetcher)
    return ThreadingHTTPServer((host, port), handler_cls)
